# Generated by Django 2.2.1 on 2019-05-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('quote_len', models.IntegerField(blank=True)),
                ('movie', models.CharField(choices=[('LOCK', 'Lock, Stock and Two Smoking Barrels'), ('SNATCH', 'Snatch')], default='LOCK', max_length=5)),
            ],
        ),
    ]
