# Generated by Django 2.2.1 on 2019-05-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='movie',
            field=models.CharField(choices=[('LO', 'Lock, Stock and Two Smoking Barrels'), ('SN', 'Snatch')], default='LO', max_length=2),
        ),
    ]
