# Generated by Django 2.2.1 on 2019-05-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='movie',
            field=models.TextField(default='Lock, Stock and Two Smoking Barrels'),
        ),
    ]
