# Generated by Django 2.2.1 on 2019-05-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='len',
            field=models.IntegerField(default=0),
        ),
    ]
