# Generated by Django 2.2.1 on 2019-05-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20190523_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_len',
        ),
    ]
