# Generated by Django 2.2.1 on 2019-05-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_len'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='len',
            new_name='quote_len',
        ),
    ]
