# Generated by Django 2.2.1 on 2019-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20190522_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_len',
            field=models.IntegerField(blank=True),
        ),
    ]
