# Generated by Django 2.2.1 on 2019-05-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20190522_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='movie',
            field=models.CharField(choices=[('LOCK', 'Lock, Stock and Two Smoking Barrels'), ('SNATCH', 'Snatch')], default='LOCK', max_length=5),
        ),
    ]
