# Generated by Django 2.2.1 on 2019-05-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_quote_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_len',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
