# Generated by Django 2.2.1 on 2019-05-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20190523_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_len',
        ),
    ]
