# Generated by Django 2.2.1 on 2019-05-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_auto_20190524_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_size',
            field=models.TextField(default=''),
        ),
    ]
